# Generated by Django 2.1.8 on 2019-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=50)),
                ('equipment_model', models.CharField(max_length=50)),
                ('equipment_uuid', models.CharField(max_length=50, unique=True)),
                ('platform_verion', models.CharField(max_length=50)),
                ('start_but_statue', models.IntegerField(default=0, max_length=1)),
                ('statue_statue', models.IntegerField(default=0, max_length=1)),
                ('gid', models.IntegerField(max_length=5, null=True)),
            ],
        ),
    ]
