# Generated by Django 2.1.8 on 2019-07-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='item_eng',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='sidetype',
            name='side_eng',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
