# Generated by Django 2.1.8 on 2019-06-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfarm', '0002_auto_20190602_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlist',
            name='report',
            field=models.IntegerField(null=True),
        ),
    ]
