# Generated by Django 2.1.8 on 2019-09-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfarm', '0002_auto_20190701_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlist',
            name='node_pid',
            field=models.IntegerField(null=True),
        ),
    ]
