# Generated by Django 2.1.8 on 2019-06-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfarm', '0003_equipmentlist_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='report',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
