# Generated by Django 2.1.8 on 2019-06-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfarm', '0004_auto_20190621_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
    ]
