# Generated by Django 2.1.8 on 2019-06-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfarm', '0005_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
