# Generated by Django 2.1.8 on 2019-06-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfarm', '0006_auto_20190626_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(max_length=64),
        ),
    ]
