# Generated by Django 2.1.8 on 2019-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfarm', '0007_auto_20190626_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SideType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
